name: Scheduled Script Execution

on:
  schedule:
    # 每天 UTC 时间 14:00 (北京时间 22:00) 执行
    - cron: '0 14 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run the script
        run: ./script.sh
